# Generated by Django 6.1.1 on 2026-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('has_learning_difficulty', models.BooleanField()),
                ('support_required', models.CharField(choices=[('reading', 'Reading'), ('math', 'Math'), ('speech', 'Speech'), ('none', 'None')], max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
